import 'package:skating_routine_app/src/models/skating_element.dart';

final List<SkatingElement> initialElements = [
  SkatingElement(
    name: 'Waltz Jump',
    code: 'W',
    type: ElementType.jump,
    minLevel: SkatingLevel.prePreliminary,
    entryEdge: Edge.outside,
    entryFoot: Foot.left,
    isToeAssist: false,
    exitEdge: Edge.outside,
    exitFoot: Foot.right,
  ),
  SkatingElement(
    name: 'Salchow',
    code: 'S',
    type: ElementType.jump,
    minLevel: SkatingLevel.prePreliminary,
    entryEdge: Edge.inside,
    entryFoot: Foot.left,
    isToeAssist: false,
    exitEdge: Edge.outside,
    exitFoot: Foot.right,
  ),
  SkatingElement(
    name: 'Toe Loop',
    code: 'T',
    type: ElementType.jump,
    minLevel: SkatingLevel.prePreliminary,
    entryEdge: Edge.outside,
    entryFoot: Foot.right,
    isToeAssist: true,
    exitEdge: Edge.outside,
    exitFoot: Foot.right,
  ),
  SkatingElement(
    name: 'Loop',
    code: 'Lo',
    type: ElementType.jump,
    minLevel: SkatingLevel.preliminary,
    entryEdge: Edge.outside,
    entryFoot: Foot.right,
    isToeAssist: false,
    exitEdge: Edge.outside,
    exitFoot: Foot.right,
  ),
  SkatingElement(
    name: 'Flip',
    code: 'F',
    type: ElementType.jump,
    minLevel: SkatingLevel.preliminary,
    entryEdge: Edge.inside,
    entryFoot: Foot.left,
    isToeAssist: true,
    exitEdge: Edge.outside,
    exitFoot: Foot.right,
  ),
  SkatingElement(
    name: 'Lutz',
    code: 'Lz',
    type: ElementType.jump,
    minLevel: SkatingLevel.juvenile,
    entryEdge: Edge.outside,
    entryFoot: Foot.left,
    isToeAssist: true,
    exitEdge: Edge.outside,
    exitFoot: Foot.right,
  ),
  SkatingElement(
    name: 'Axel',
    code: 'A',
    type: ElementType.jump,
    minLevel: SkatingLevel.juvenile,
    entryEdge: Edge.outside,
    entryFoot: Foot.left,
    isToeAssist: false,
    exitEdge: Edge.outside,
    exitFoot: Foot.right,
  ),
];
