name: skating_routine_app
description: "A Flutter app to help figure skaters build well-balanced routines."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-268.0.dev

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
