// Mocks generated by Mockito 5.4.6 from annotations
// in skating_routine_app/test/ui/screens/routine_builder_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:skating_routine_app/src/models/routine.dart' as _i3;
import 'package:skating_routine_app/src/models/skating_element.dart' as _i4;
import 'package:skating_routine_app/src/providers/routine_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RoutineProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutineProvider extends _i1.Mock implements _i2.RoutineProvider {
  MockRoutineProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Routine> get routines =>
      (super.noSuchMethod(
            Invocation.getter(#routines),
            returnValue: <_i3.Routine>[],
          )
          as List<_i3.Routine>);

  @override
  List<_i4.SkatingElement> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i4.SkatingElement>[],
          )
          as List<_i4.SkatingElement>);

  @override
  Map<int, bool> get validationErrors =>
      (super.noSuchMethod(
            Invocation.getter(#validationErrors),
            returnValue: <int, bool>{},
          )
          as Map<int, bool>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> searchElements(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchElements, [query]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadRoutines(int? userId) =>
      (super.noSuchMethod(
            Invocation.method(#loadRoutines, [userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setActiveRoutine(_i3.Routine? routine) => super.noSuchMethod(
    Invocation.method(#setActiveRoutine, [routine]),
    returnValueForMissingStub: null,
  );

  @override
  void addElementToRoutine(_i4.SkatingElement? element) => super.noSuchMethod(
    Invocation.method(#addElementToRoutine, [element]),
    returnValueForMissingStub: null,
  );

  @override
  void removeElementFromRoutine(int? index) => super.noSuchMethod(
    Invocation.method(#removeElementFromRoutine, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void reorderElement(int? oldIndex, int? newIndex) => super.noSuchMethod(
    Invocation.method(#reorderElement, [oldIndex, newIndex]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> saveActiveRoutine() =>
      (super.noSuchMethod(
            Invocation.method(#saveActiveRoutine, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
